name: Deploy Talk
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Create and deploy a glob to ~wannec-dozzod-marzod (devstream)"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.JANEWAY_SERVICE_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Build Frontend
        working-directory: ./ui
        run: | 
          npm ci
          npm run build:chat
      - id: glob
        uses: ./.github/actions/glob
        with:
          folder: 'ui/dist/*'
          docket: 'talk/desk.docket-0'
      - name: Commit Glob
        uses: EndBug/add-and-commit@v9
        with:
          add: 'talk/desk.docket-0'
          push: false
          message: 'update glob: ${{ steps.glob.outputs.hash }} [skip actions]'
      - name: Push Glob
        uses: EndBug/add-and-commit@v9
        with:
          pull: 'origin master'
      - uses: ./.github/actions/release
        with:
          app: 'talk'
          ship: 'devstream'
          credentials: ${{ secrets.JANEWAY_SERVICE_KEY }}
          ssh-sec-key: ${{ secrets.JANEWAY_SSH_SEC_KEY }}
          ssh-pub-key: ${{ secrets.JANEWAY_SSH_PUB_KEY }}