name: Deploy Groups (canary)
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Create and deploy a glob to ~binnec-dozzod-marzod (canary)"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          app: 'groups'
          ship: 'canary'
          credentials: ${{ secrets.JANEWAY_SERVICE_KEY }}
          ssh-sec-key: ${{ secrets.JANEWAY_SSH_SEC_KEY }}
          ssh-pub-key: ${{ secrets.JANEWAY_SSH_PUB_KEY }}