name: Master Release
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./main/ui
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/setup-python@v3
        with:
          python-version: '2.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests argparse
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Get Urbit
        working-directory: ./
        run: |
          pwd
          curl -JLO https://urbit.org/install/linux64/latest
          tar zxvf ./linux64.tgz --strip-components=1 --strip=1
      - name: Get Urbit Repo
        uses: actions/checkout@v3
        with:
          lfs: true
          repository: urbit/urbit
          path: urbit-repo
      - name: Get LFS
        working-directory: urbit-repo
        run: |
          pwd
          git lfs pull
      - name: Boot Fakezod
        working-directory: ./
        run: ./urbit -dF zod -B urbit-repo/bin/multi.pill
      - name: Mount Desk
        working-directory: urbit-repo/pkg/herb
        run: |
          ./herb ../../../zod -p hood -d '+hood/mount %base'
      - name: Install Packages & Build
        run: |
          npm install
          npm run build
          rsync -avL --delete dist/* ../../zod/base/homestead/
      - name: Make and Update Glob
        working-directory: urbit-repo/pkg/herb
        run: |
          echo "committing base"
          ./herb ../../../zod -p hood -d '+hood/commit %base'
          sleep 5s
          ls -al ../../../zod/.urb/put
          echo "globbing homestead"
          ./herb ../../../zod -d='-garden!make-glob %base /homestead'
          ls -al ../../../zod/.urb/put
          echo "exiting"
          ./herb ../../../zod -p hood -d '+hood/exit'
      